language: node_js
node_js:
- 0.1
script:
- npm test
env:
  global:
  - secure: bOy9yOUK1LJhJcNtrlvrJz4DL8prlGH2oixprSL5uQFreUe452RESP9uUQ+zWObuuqXN0zNI0CvbLslOmrCxbwOavY89oboP3S5R+hd80PjdlhVw454No6Jh3TBlbsaNxeqdckHTPde5UYA3q4tmgaSuOiv84J8Xms8kzU6pQX8=
  - secure: DHsA4Qrh3YZjvoYTaY03q9zKvkmUXvV8uw8yJHXuhLqyiZKI5ATtQ/1IBZDGbb0bRrtx0UEE0VSz+k/OWWK3yptEpQKgTi1sBsnjQ7NGbMbepUpH7hlOFwsS+x1Kg5cji6Qgu6dffY1oL07It8KPpEOOakprjNp6tTXVDI5WP4E=
