language: node_js
node_js:
- 0.1
script:
- npm run ci
env:
  global:
  - secure: U/3fMVCZfV4abh9Y6D3z2QxBZGWdDsCLIs6f8Wble6RV3ROMaW5DE4dhu6aUCBvtUTTRi5qeGDQF9Zu+uFjWqBxmvS6JYEMerZBy3lTwU5dMRcFDD+2hEITM/ERqqzIBQnGR6fQ60tlJCkSt0GU5atPetk8FyoOK97H64UEaBjs=
  - secure: F2rn1VeuKxLUW1jQ+4524Y5/TEZ+l2Lss3VJKQNo1eagk8yGbbvcg+IBX59sl61RfEj0icXDhjuNIBVqFe0e6cVy7l4DGt8l4xGvEPmh823rGAncti3xCOmDMhUnPSVUbRqsbR0d6b+guL5NZDsoI47hl98f9rUaRXaXFFLBJNM=
